### ISSUE TITLE
Changes and enhancements to make the Ansible deploy and tests more solid and stable

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-cloudformation#24]
There are some changes that would make the environment setup more solid and would ease the testing process.

### Tasks

- [x] Enable Elasticsearch

- [x] Enable Kibana

- [x] Enable Wazuh-Manager Wazuh-API and Filebeat

- [x] Enable ES logging to file

- [x] Open port 5986 in Windows instance

- [x] Evaluate how to access to port 9200 in ES instances for tests

- [x] Evaluate how to access to port 55000 in Wazuh Master instance for tests

- [x] Ensure Suricata is properly configured after bumping

- [x] Update Virustotal regex to accept Windows Paths

Best regards,

Jose
