### ISSUE TITLE
Wazuh Release 3.11.1_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-cloudformation#37]
Wazuh version: 3.11.1
Elastic version: 7.5.1

### Tasks

- [ ] Adapt to new versions (3.11.1 - 7.5.1)

- [ ] Check templates and update them if needed

- [ ] Tests

- [ ] Update changelog

- [ ] Tag: v3.11.1_7.5.1

- [ ] Update documentation references

- [ ] Draft release
