### ISSUE TITLE
Wazuh CF template does not create EIP for all instances

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-cloudformation#39]
@jm404 commented on [Tue Jan 14 2020](https://github.com/wazuh/wazuh-automation/issues/200)

Hi team,

We recently diagnosed that the EIP relative to the Wazuh Master is not being associated properly and some instance does not have their own EIP.

### Tasks

- [x] Fix Wazuh Master EIP

- [x] Review CF template and implement required changes to create EIP for all instances

### Tests

- [x] Update a CF Stack and ensure the EIP's are correctly created and assigned

- [x] Create a CF Stack and ensure the EIP's are correctly created and assigned

Best regards,

Jose

**Comment by jm404** [comment]
### Update Wazuh Template

The [wazuh-template](https://github.com/wazuh/wazuh-cloudformation/blob/master/wazuh_template.yml) has been updated to fix the Wazuh Maste Network interface block and add required EIP for Kibana, ES and Splunk

A representative example of the change applied:

![image](https://user-images.githubusercontent.com/46649922/72441459-0588ad00-37ab-11ea-943f-baf6e43b8b1b.png)


You can check the changes at https://github.com/wazuh/wazuh-cloudformation/commit/634dd791de13213d90e22b171fbbc8d8bda5b689
